# 
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenUM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.

include ${BUILD_DIR}/src/tools.mk



#
#  PHYMOD PHY8806X SUPPORT
#
ifneq ($(filter PHY8806X, $(PHYMOD_LIST)),)
BOBJS += libs/phymod/chip/phy8806x/tier1/phy8806x_tsc_dependencies.o
BOBJS += libs/phymod/chip/phy8806x/tier1/phy8806x_tsc_functions.o
BOBJS += libs/phymod/chip/phy8806x/tier1/phy8806x_cfg_seq.o
BOBJS += libs/phymod/chip/phy8806x/tier2/phy8806x_diagnostics.o
BOBJS += libs/phymod/chip/phy8806x/phy8806x_pe_api.o
BOBJS += libs/phymod/chip/phy8806x/phy8806x.o
BOBJS += libs/phymod/chip/phy8806x/phy8806x_diagnostics_dispatch.o
BOBJS += libs/phymod/chip/phy8806x/phy8806x_xmod_arg_len.o
BOBJS += libs/phymod/chip/phy8806x/phy8806x_dispatch.o
endif


#
#  PHYMOD FALCON SUPPORT
#
ifneq ($(filter FALCON, $(PHYMOD_LIST)),)
BOBJS += libs/phymod/chip/falcon/falcon_diagnostics_dispatch.o
BOBJS += libs/phymod/chip/falcon/falcon_dispatch.o
BOBJS += libs/phymod/chip/falcon/tier1/falcon_cfg_seq.o
BOBJS += libs/phymod/chip/falcon/tier1/falcon_tsc_functions.o
BOBJS += libs/phymod/chip/falcon/tier1/falcon_cfg_seq.o
BOBJS += libs/phymod/chip/falcon/tier1/falcon_tsc_dependencies.o
BOBJS += libs/phymod/chip/falcon/tier2/falcon.o
BOBJS += libs/phymod/chip/falcon/tier2/tscf_ucode.o
BOBJS += libs/phymod/chip/falcon/tier2/falcon_diagnostics.o
BOBJS += libs/phymod/sym/chip/bcmi_falcon_xgxs_sym.o
BOBJS += libs/phymod/sim/chip/falcon_sim.o
endif


#
#  PHYMOD HURACAN SUPPORT
#
ifneq ($(filter HURACAN, $(PHYMOD_LIST)),)
BOBJS += libs/phymod/chip/huracan/tier1/huracan_reg_access.o
BOBJS += libs/phymod/chip/huracan/tier1/huracan_cfg_seq.o
BOBJS += libs/phymod/chip/huracan/tier2/huracan_diagnostics.o
BOBJS += libs/phymod/chip/huracan/tier2/huracan.o
BOBJS += libs/phymod/chip/huracan/tier1/huracan_pkg_cfg.o
BOBJS += libs/phymod/chip/huracan/huracan_dispatch.o
BOBJS += libs/phymod/chip/huracan/huracan_diagnostics_dispatch.o
endif

#
#  PHYMOD QUADRA28 SUPPORT
#
ifneq ($(filter QUADRA28, $(PHYMOD_LIST)),)
OPTION_CFLAGS += -I$(SDK_DIR)/libs/phymod/chip/quadra28/tier1 
BOBJS += libs/phymod/chip/quadra28/tier1/quadra28_serdes/merlin_quadra28_dependencies.o
BOBJS += libs/phymod/chip/quadra28/tier1/quadra28_serdes/merlin_quadra28_functions.o
BOBJS += libs/phymod/chip/quadra28/tier1/quadra28_reg_access.o
BOBJS += libs/phymod/chip/quadra28/tier1/quadra28_ucode.o
BOBJS += libs/phymod/chip/quadra28/tier1/quadra28_cfg_seq.o
BOBJS += libs/phymod/chip/quadra28/tier1/quadra28_micro_seq.o
BOBJS += libs/phymod/chip/quadra28/tier2/quadra28_diagnostics.o
BOBJS += libs/phymod/chip/quadra28/tier2/quadra28.o
BOBJS += libs/phymod/chip/quadra28/quadra28_dispatch.o
BOBJS += libs/phymod/chip/quadra28/quadra28_diagnostics_dispatch.o
endif

#
#  PHYMOD QUADRA28 SUPPORT
#
ifneq ($(filter MADURA, $(PHYMOD_LIST)),)
BOBJS += libs/phymod/chip/madura/tier1/flashing_ucode.o
BOBJS += libs/phymod/chip/madura/tier1/madura_serdes/falcon_madura_src/falcon_madura_dependencies.o
BOBJS += libs/phymod/chip/madura/tier1/madura_serdes/falcon_madura_src/falcon_madura_functions.o
BOBJS += libs/phymod/chip/madura/tier1/madura_serdes/falcon2_madura_src/falcon2_madura_functions.o 
BOBJS += libs/phymod/chip/madura/tier1/madura_serdes/falcon2_madura_src/falcon2_madura_dependencies.o 
BOBJS += libs/phymod/chip/madura/tier1/slave_ucode.o
BOBJS += libs/phymod/chip/madura/tier1/madura_cfg_seq.o
BOBJS += libs/phymod/chip/madura/tier1/madura_diag_seq.o
BOBJS += libs/phymod/chip/madura/tier1/master_ucode.o
BOBJS += libs/phymod/chip/madura/tier2/madura_diagnostics.o
BOBJS += libs/phymod/chip/madura/tier2/madura.o
BOBJS += libs/phymod/chip/madura/madura_dispatch.o
BOBJS += libs/phymod/chip/madura/madura_diagnostics_dispatch.o
endif

#
#  PHYMOD SESTO SUPPORT
#
ifneq ($(filter SESTO, $(PHYMOD_LIST)),)
BOBJS += libs/phymod/chip/sesto/tier1/sesto_serdes/merlin_sesto_src/merlin_sesto_dependencies.o
BOBJS += libs/phymod/chip/sesto/tier1/sesto_serdes/merlin_sesto_src/merlin_sesto_functions.o
BOBJS += libs/phymod/chip/sesto/tier1/sesto_serdes/falcon_furia_sesto_src/falcon_furia_sesto_dependencies.o
BOBJS += libs/phymod/chip/sesto/tier1/sesto_serdes/falcon_furia_sesto_src/falcon_furia_sesto_functions.o
BOBJS += libs/phymod/chip/sesto/tier1/sesto_cfg_seq.o
BOBJS += libs/phymod/chip/sesto/tier1/sesto_diag_seq.o
BOBJS += libs/phymod/chip/sesto/tier1/falcon_ucode.o
BOBJS += libs/phymod/chip/sesto/tier1/merlin_ucode.o
BOBJS += libs/phymod/chip/sesto/tier2/sesto.o
BOBJS += libs/phymod/chip/sesto/tier2/sesto_diagnostics.o
BOBJS += libs/phymod/chip/sesto/sesto_diagnostics_dispatch.o
BOBJS += libs/phymod/chip/sesto/sesto_dispatch.o
endif

#
#  PHYMOD QTCE SUPPORT
#
ifneq ($(filter QTCE, $(PHYMOD_LIST)),)
BOBJS += libs/phymod/chip/qtce/tier1/qmod_sc_lkup_table.o
BOBJS += libs/phymod/chip/qtce/tier1/qmod_diagnostics.o
BOBJS += libs/phymod/chip/qtce/tier1/qmod_cfg_seq.o
BOBJS += libs/phymod/chip/qtce/tier1/qmod_enum_defines.o
BOBJS += libs/phymod/chip/qtce/tier2/qtce_diagnostics.o
BOBJS += libs/phymod/chip/qtce/tier2/qtce_ucode.o
BOBJS += libs/phymod/chip/qtce/tier2/qtce.o
BOBJS += libs/phymod/chip/qtce/qtce_dispatch.o
BOBJS += libs/phymod/chip/qtce/qtce_diagnostics_dispatch.o
endif

#
#  PHYMOD FURIA SUPPORT
#
ifneq ($(filter FURIA, $(PHYMOD_LIST)),)
BOBJS += libs/phymod/chip/furia/tier1/falcon_furia_src/falcon_furia_dependencies.o
BOBJS += libs/phymod/chip/furia/tier1/falcon_furia_src/falcon_furia_functions.o
BOBJS += libs/phymod/chip/furia/tier1/furia_cfg_seq.o
BOBJS += libs/phymod/chip/furia/tier1/furia_micro_seq.o
BOBJS += libs/phymod/chip/furia/tier1/furia_ucode.o
BOBJS += libs/phymod/chip/furia/tier1/furia_pkg_cfg.o
BOBJS += libs/phymod/chip/furia/tier1/furia_reg_access.o
BOBJS += libs/phymod/chip/furia/tier2/furia_diagnostics.o
BOBJS += libs/phymod/chip/furia/tier2/furia.o
BOBJS += libs/phymod/chip/furia/furia_diagnostics_dispatch.o
BOBJS += libs/phymod/chip/furia/furia_dispatch.o
BOBJS += libs/phymod/chip/furia_82212/furia_82212_dispatch.o
BOBJS += libs/phymod/chip/furia_82212/furia_82212_diagnostics_dispatch.o 
BOBJS += libs/phymod/chip/furia_82212/tier2/furia_82212_diagnostics.o
BOBJS += libs/phymod/chip/furia_82212/tier2/furia_82212.o
endif

#
#  PHYMOD VIPER SUPPORT
#
ifneq ($(filter VIPER, $(PHYMOD_LIST)),)
BOBJS += libs/phymod/chip/viper/tier1/viper_dependencies.o
BOBJS += libs/phymod/chip/viper/tier1/viper_pmd_cfg_seq.o
BOBJS += libs/phymod/chip/viper/tier2/viper_diagnostics.o
BOBJS += libs/phymod/chip/viper/tier2/viper.o
BOBJS += libs/phymod/chip/viper/viper_dispatch.o
BOBJS += libs/phymod/chip/viper/viper_diagnostics_dispatch.o
BOBJS += libs/phymod/sim/chip/viper_sim.o
BOBJS += libs/phymod/sym/chip/bcmi_viper_xgxs_sym.o
BOBJS += libs/phymod/sym/chip/bcmi_sgmiip2x4_serdes_sym.o
endif

#
#  PHYMOD TSCF SUPPORT
#
ifneq ($(filter TSCF, $(PHYMOD_LIST)),)
BOBJS += libs/phymod/chip/tscf/tier1/tefmod_cfg_seq.o
BOBJS += libs/phymod/chip/tscf/tier1/tefmod_enum_defines.o
BOBJS += libs/phymod/chip/tscf/tier1/tefmod_sc_lkup_table.o
BOBJS += libs/phymod/chip/tscf/tier1/tefmod_diagnostics.o
BOBJS += libs/phymod/chip/tscf/tier2/tscf_diagnostics.o
BOBJS += libs/phymod/chip/tscf/tier2/tscf.o
BOBJS += libs/phymod/chip/tscf/tscf_dispatch.o
BOBJS += libs/phymod/chip/tscf/tscf_diagnostics_dispatch.o
BOBJS += libs/phymod/sim/chip/tscf_sim.o
BOBJS += libs/phymod/sym/chip/bcmi_tscf_xgxs_sym.o
endif

#
#  PHYMOD TSCE SUPPORT
#
ifneq ($(filter TSCE, $(PHYMOD_LIST)),)
BOBJS += libs/phymod/chip/tsce/tier1/temod_sc_lkup_table.o
BOBJS += libs/phymod/chip/tsce/tier1/temod_diagnostics.o
BOBJS += libs/phymod/chip/tsce/tier1/temod_cfg_seq.o
BOBJS += libs/phymod/chip/tsce/tier1/temod_enum_defines.o
BOBJS += libs/phymod/chip/tsce/tier2/tsce_diagnostics.o
BOBJS += libs/phymod/chip/tsce/tier2/tsce_ucode.o
BOBJS += libs/phymod/chip/tsce/tier2/tsce.o
BOBJS += libs/phymod/chip/tsce/tsce_dispatch.o
BOBJS += libs/phymod/chip/tsce/bcmi_tsce_xgxs_resetval.o
BOBJS += libs/phymod/chip/tsce/tsce_diagnostics_dispatch.o
BOBJS += libs/phymod/sym/chip/bcmi_tsce_xgxs_sym.o
BOBJS += libs/phymod/sim/chip/tsce_sim.o
endif

ifneq ($(filter TSCE_DPLL, $(PHYMOD_LIST)),)
BOBJS += libs/phymod/chip/tsce_dpll/tier1/temod_dpll_cfg_seq.o
BOBJS += libs/phymod/chip/tsce_dpll/tier1/temod_dpll_diagnostics.o
BOBJS += libs/phymod/chip/tsce_dpll/tier1/temod_dpll_enum_defines.o
BOBJS += libs/phymod/chip/tsce_dpll/tier1/temod_dpll_sc_lkup_table.o
BOBJS += libs/phymod/chip/tsce_dpll/tier2/tsce_dpll.o
BOBJS += libs/phymod/chip/tsce_dpll/tier2/tsce_dpll_diagnostics.o
BOBJS += libs/phymod/chip/tsce_dpll/tsce_dpll_diagnostics_dispatch.o
BOBJS += libs/phymod/chip/tsce_dpll/tsce_dpll_dispatch.o
BOBJS += libs/phymod/sym/chip/bcmi_eagle_dpll_xgxs_sym.o
endif

#
#  PHYMOD QSGMIIE SUPPORT
#
ifneq ($(filter QSGMIIE, $(PHYMOD_LIST)),)
BOBJS += libs/phymod/chip/qsgmiie/tier1/tqmod_cfg_seq.o
BOBJS += libs/phymod/chip/qsgmiie/tier2/qsgmiie_diagnostics.o
BOBJS += libs/phymod/chip/qsgmiie/tier2/qsgmiie.o
BOBJS += libs/phymod/chip/qsgmiie/qsgmiie_diagnostics_dispatch.o
BOBJS += libs/phymod/chip/qsgmiie/qsgmiie_dispatch.o
BOBJS += libs/phymod/chip/qsgmiie/bcmi_qsgmiie_serdes_resetval.o
BOBJS += libs/phymod/chip/falcon/tier1/falcon_tsc_dependencies.o
BOBJS += libs/phymod/chip/falcon/tier1/falcon_tsc_functions.o
BOBJS += libs/phymod/chip/falcon/tier1/falcon_cfg_seq.o
BOBJS += libs/phymod/chip/falcon/tier2/tscf_ucode.o
BOBJS += libs/phymod/chip/falcon/tier2/falcon_diagnostics.o
BOBJS += libs/phymod/chip/falcon/tier2/falcon.o
BOBJS += libs/phymod/chip/falcon/falcon_diagnostics_dispatch.o
BOBJS += libs/phymod/chip/falcon/falcon_dispatch.o
BOBJS += libs/phymod/sym/chip/bcmi_qsgmiie_serdes_sym.o
BOBJS += libs/phymod/sim/chip/qsgmiie_sim.o
endif

#
#  PHYMOD EAGLE SUPPORT
#
ifneq ($(filter EAGLE, $(PHYMOD_LIST)),)
BOBJS += libs/phymod/chip/eagle/tier1/eagle_tsc_dependencies.o
BOBJS += libs/phymod/chip/eagle/tier1/eagle_tsc_functions.o
BOBJS += libs/phymod/chip/eagle/tier1/eagle_cfg_seq.o
BOBJS += libs/phymod/chip/eagle/tier2/eagle_common.o
BOBJS += libs/phymod/chip/eagle/tier2/eagle.o
BOBJS += libs/phymod/chip/eagle/tier2/eagle_diagnostics.o
BOBJS += libs/phymod/chip/eagle/eagle_diagnostics_dispatch.o
BOBJS += libs/phymod/chip/eagle/eagle_dispatch.o
BOBJS += libs/phymod/sim/chip/eagle_sim.o
BOBJS += libs/phymod/sym/chip/bcmi_eagle_xgxs_sym.o
endif
ifneq ($(filter EAGLE_DPLL, $(PHYMOD_LIST)),)
BOBJS += libs/phymod/chip/eagle_dpll/eagle_dpll_diagnostics_dispatch.o
BOBJS += libs/phymod/chip/eagle_dpll/eagle_dpll_dispatch.o
BOBJS += libs/phymod/chip/eagle_dpll/tier1/eagle2_cfg_seq.o
BOBJS += libs/phymod/chip/eagle_dpll/tier1/eagle2_tsc2pll_dependencies.o
BOBJS += libs/phymod/chip/eagle_dpll/tier1/eagle2_tsc2pll_functions.o
BOBJS += libs/phymod/chip/eagle_dpll/tier2/eagle2_tsc2pll_ucode.o
BOBJS += libs/phymod/chip/eagle_dpll/tier2/eagle_dpll.o
BOBJS += libs/phymod/chip/eagle_dpll/tier2/eagle_dpll_diagnostics.o
endif
#
#  PHYMOD SGMIIP2X4 SUPPORT
#
ifneq ($(filter SGMIIP2X4, $(PHYMOD_LIST)),)
BOBJS += libs/phymod/chip/sgmiip2x4/sgmiip2x4_dispatch.o
BOBJS += libs/phymod/chip/sgmiip2x4/sgmiip2x4_diagnostics_dispatch.o
BOBJS += libs/phymod/chip/sgmiip2x4/tier1/sgmiip2x4_pmd_cfg_seq.o
BOBJS += libs/phymod/chip/sgmiip2x4/tier2/sgmiip2x4_diagnostics.o
BOBJS += libs/phymod/chip/sgmiip2x4/tier2/sgmiip2x4.o
BOBJS += libs/phymod/sym/chip/bcmi_sgmiip2x4_serdes_sym.o
endif

BOBJS += libs/phymod/util/phymod_util.o
BOBJS += libs/phymod/sim/phymod_sim.o
BOBJS += libs/phymod/sym/phymod_symbols_index.o
BOBJS += libs/phymod/sym/phymod_symbol_field_filter.o
BOBJS += libs/phymod/sym/phymod_symbol_show_fields.o
BOBJS += libs/phymod/sym/phymod_symbol_fields.o
BOBJS += libs/phymod/sym/phymod_symbol_dump.o
BOBJS += libs/phymod/sym/phymod_symbol.o
BOBJS += libs/phymod/sym/phymod_symbols_iter.o
BOBJS += libs/phymod/sym/phymod_symbols_get.o
BOBJS += libs/phymod/diag/phymod_diag.o
BOBJS += libs/phymod/core/phymod_debug.o
BOBJS += libs/phymod/core/phymod_diagnostics_enums.o
BOBJS += libs/phymod/core/phymod_acc.o
BOBJS += libs/phymod/core/phymod.o
BOBJS += libs/phymod/core/phymod_diagnostics_dispatch.o
BOBJS += libs/phymod/core/phymod_enums.o
BOBJS += libs/phymod/core/phymod_dispatch.o
BOBJS += libs/phymod/acc/phymod_tsc_iblk.o


include rules.mk

 
