/*
 * $Id: chipman.pm,v 1.2.2.1 2016/03/18 08:18:35 justinch Exp n *
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenUM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 */
#include <system.h>
const char bcm5354x_pmq_pport_to_blockid[] = 
{ 
                              -1,                               -1,                    PMQ0_BLOCK_ID,                    PMQ0_BLOCK_ID, /* Physical port 0 ~ 3 */
                   PMQ0_BLOCK_ID,                    PMQ0_BLOCK_ID,                    PMQ0_BLOCK_ID,                    PMQ0_BLOCK_ID, /* Physical port 4 ~ 7 */
                   PMQ0_BLOCK_ID,                    PMQ0_BLOCK_ID,                    PMQ0_BLOCK_ID,                    PMQ0_BLOCK_ID, /* Physical port 8 ~ 11 */
                   PMQ0_BLOCK_ID,                    PMQ0_BLOCK_ID,                    PMQ0_BLOCK_ID,                    PMQ0_BLOCK_ID, /* Physical port 12 ~ 15 */
                   PMQ0_BLOCK_ID,                    PMQ0_BLOCK_ID,                    PMQ1_BLOCK_ID,                    PMQ1_BLOCK_ID, /* Physical port 16 ~ 19 */
                   PMQ1_BLOCK_ID,                    PMQ1_BLOCK_ID,                    PMQ1_BLOCK_ID,                    PMQ1_BLOCK_ID, /* Physical port 20 ~ 23 */
                   PMQ1_BLOCK_ID,                    PMQ1_BLOCK_ID,                    PMQ1_BLOCK_ID,                    PMQ1_BLOCK_ID, /* Physical port 24 ~ 27 */
                   PMQ1_BLOCK_ID,                    PMQ1_BLOCK_ID,                    PMQ1_BLOCK_ID,                    PMQ1_BLOCK_ID, /* Physical port 28 ~ 31 */
                   PMQ1_BLOCK_ID,                    PMQ1_BLOCK_ID,                    PMQ2_BLOCK_ID,                    PMQ2_BLOCK_ID, /* Physical port 32 ~ 35 */
                   PMQ2_BLOCK_ID,                    PMQ2_BLOCK_ID,                    PMQ2_BLOCK_ID,                    PMQ2_BLOCK_ID, /* Physical port 36 ~ 39 */
                   PMQ2_BLOCK_ID,                    PMQ2_BLOCK_ID,                                                                      /* Physical port 40 ~ 42 */
};
const char bcm5354x_pmq_pport_to_index_in_block[] = 
{ 
   0,    0,    0,    1, /* Physical port 0 ~ 3 */
   2,    3,    4,    5, /* Physical port 4 ~ 7 */
   6,    7,    8,    9, /* Physical port 8 ~ 11 */
  10,   11,   12,   13, /* Physical port 12 ~ 15 */
  14,   15,    0,    1, /* Physical port 16 ~ 19 */
   2,    3,    4,    5, /* Physical port 20 ~ 23 */
   6,    7,    8,    9, /* Physical port 24 ~ 27 */
  10,   11,   12,   13, /* Physical port 28 ~ 31 */
  14,   15,    0,    1, /* Physical port 32 ~ 35 */
   2,    3,    4,    5, /* Physical port 36 ~ 39 */
   6,    7, };
char bcm5354x_pmq_lport_to_blockid[BCM5354X_LPORT_MAX + 1] = { -1 }; 
char bcm5354x_pmq_lport_to_index_in_block[BCM5354X_LPORT_MAX + 1] = { -1 }; 
const char bcm5354x_gport_pport_to_blockid[] = 
{ 
                              -1,                               -1,                  GPORT0_BLOCK_ID,                  GPORT0_BLOCK_ID, /* Physical port 0 ~ 3 */
                 GPORT0_BLOCK_ID,                  GPORT0_BLOCK_ID,                  GPORT0_BLOCK_ID,                  GPORT0_BLOCK_ID, /* Physical port 4 ~ 7 */
                 GPORT0_BLOCK_ID,                  GPORT0_BLOCK_ID,                  GPORT1_BLOCK_ID,                  GPORT1_BLOCK_ID, /* Physical port 8 ~ 11 */
                 GPORT1_BLOCK_ID,                  GPORT1_BLOCK_ID,                  GPORT1_BLOCK_ID,                  GPORT1_BLOCK_ID, /* Physical port 12 ~ 15 */
                 GPORT1_BLOCK_ID,                  GPORT1_BLOCK_ID,                  GPORT2_BLOCK_ID,                  GPORT2_BLOCK_ID, /* Physical port 16 ~ 19 */
                 GPORT2_BLOCK_ID,                  GPORT2_BLOCK_ID,                  GPORT2_BLOCK_ID,                  GPORT2_BLOCK_ID, /* Physical port 20 ~ 23 */
                 GPORT2_BLOCK_ID,                  GPORT2_BLOCK_ID,                  GPORT3_BLOCK_ID,                  GPORT3_BLOCK_ID, /* Physical port 24 ~ 27 */
                 GPORT3_BLOCK_ID,                  GPORT3_BLOCK_ID,                  GPORT3_BLOCK_ID,                  GPORT3_BLOCK_ID, /* Physical port 28 ~ 31 */
                 GPORT3_BLOCK_ID,                  GPORT3_BLOCK_ID,                  GPORT4_BLOCK_ID,                  GPORT4_BLOCK_ID, /* Physical port 32 ~ 35 */
                 GPORT4_BLOCK_ID,                  GPORT4_BLOCK_ID,                  GPORT4_BLOCK_ID,                  GPORT4_BLOCK_ID, /* Physical port 36 ~ 39 */
                 GPORT4_BLOCK_ID,                  GPORT4_BLOCK_ID,                                                                      /* Physical port 40 ~ 42 */
};
const char bcm5354x_gport_pport_to_index_in_block[] = 
{ 
   0,    0,    0,    1, /* Physical port 0 ~ 3 */
   2,    3,    4,    5, /* Physical port 4 ~ 7 */
   6,    7,    0,    1, /* Physical port 8 ~ 11 */
   2,    3,    4,    5, /* Physical port 12 ~ 15 */
   6,    7,    0,    1, /* Physical port 16 ~ 19 */
   2,    3,    4,    5, /* Physical port 20 ~ 23 */
   6,    7,    0,    1, /* Physical port 24 ~ 27 */
   2,    3,    4,    5, /* Physical port 28 ~ 31 */
   6,    7,    0,    1, /* Physical port 32 ~ 35 */
   2,    3,    4,    5, /* Physical port 36 ~ 39 */
   6,    7, };
char bcm5354x_gport_lport_to_blockid[BCM5354X_LPORT_MAX + 1] = { -1 }; 
char bcm5354x_gport_lport_to_index_in_block[BCM5354X_LPORT_MAX + 1] = { -1 }; 
const char bcm5354x_pgw_ge_pport_to_blockid[] = 
{ 
                              -1,                               -1,                 PGW_GE0_BLOCK_ID,                 PGW_GE0_BLOCK_ID, /* Physical port 0 ~ 3 */
                PGW_GE0_BLOCK_ID,                 PGW_GE0_BLOCK_ID,                 PGW_GE0_BLOCK_ID,                 PGW_GE0_BLOCK_ID, /* Physical port 4 ~ 7 */
                PGW_GE0_BLOCK_ID,                 PGW_GE0_BLOCK_ID,                 PGW_GE0_BLOCK_ID,                 PGW_GE0_BLOCK_ID, /* Physical port 8 ~ 11 */
                PGW_GE0_BLOCK_ID,                 PGW_GE0_BLOCK_ID,                 PGW_GE0_BLOCK_ID,                 PGW_GE0_BLOCK_ID, /* Physical port 12 ~ 15 */
                PGW_GE0_BLOCK_ID,                 PGW_GE0_BLOCK_ID,                 PGW_GE1_BLOCK_ID,                 PGW_GE1_BLOCK_ID, /* Physical port 16 ~ 19 */
                PGW_GE1_BLOCK_ID,                 PGW_GE1_BLOCK_ID,                 PGW_GE1_BLOCK_ID,                 PGW_GE1_BLOCK_ID, /* Physical port 20 ~ 23 */
                PGW_GE1_BLOCK_ID,                 PGW_GE1_BLOCK_ID,                 PGW_GE1_BLOCK_ID,                 PGW_GE1_BLOCK_ID, /* Physical port 24 ~ 27 */
                PGW_GE1_BLOCK_ID,                 PGW_GE1_BLOCK_ID,                 PGW_GE1_BLOCK_ID,                 PGW_GE1_BLOCK_ID, /* Physical port 28 ~ 31 */
                PGW_GE1_BLOCK_ID,                 PGW_GE1_BLOCK_ID,                 PGW_GE2_BLOCK_ID,                 PGW_GE2_BLOCK_ID, /* Physical port 32 ~ 35 */
                PGW_GE2_BLOCK_ID,                 PGW_GE2_BLOCK_ID,                 PGW_GE2_BLOCK_ID,                 PGW_GE2_BLOCK_ID, /* Physical port 36 ~ 39 */
                PGW_GE2_BLOCK_ID,                 PGW_GE2_BLOCK_ID,                                                                      /* Physical port 40 ~ 42 */
};
const char bcm5354x_pgw_ge_pport_to_index_in_block[] = 
{ 
   0,    0,    0,    1, /* Physical port 0 ~ 3 */
   2,    3,    4,    5, /* Physical port 4 ~ 7 */
   6,    7,    8,    9, /* Physical port 8 ~ 11 */
  10,   11,   12,   13, /* Physical port 12 ~ 15 */
  14,   15,    0,    1, /* Physical port 16 ~ 19 */
   2,    3,    4,    5, /* Physical port 20 ~ 23 */
   6,    7,    8,    9, /* Physical port 24 ~ 27 */
  10,   11,   12,   13, /* Physical port 28 ~ 31 */
  14,   15,    0,    1, /* Physical port 32 ~ 35 */
   2,    3,    4,    5, /* Physical port 36 ~ 39 */
   6,    7, };
char bcm5354x_pgw_ge_lport_to_blockid[BCM5354X_LPORT_MAX + 1] = { -1 }; 
char bcm5354x_pgw_ge_lport_to_index_in_block[BCM5354X_LPORT_MAX + 1] = { -1 }; 



void bcm5354x_init_port_block_map(uint16 devid, uint16 revid) { 
     int pport;
     sal_memset(bcm5354x_pmq_lport_to_blockid, -1, BCM5354X_LPORT_MAX);
     sal_memset(bcm5354x_pmq_lport_to_index_in_block, 0, BCM5354X_LPORT_MAX); 
     sal_memset(bcm5354x_gport_lport_to_blockid, -1, BCM5354X_LPORT_MAX);
     sal_memset(bcm5354x_gport_lport_to_index_in_block, 0, BCM5354X_LPORT_MAX); 
     sal_memset(bcm5354x_pgw_ge_lport_to_blockid, -1, BCM5354X_LPORT_MAX);
     sal_memset(bcm5354x_pgw_ge_lport_to_index_in_block, 0, BCM5354X_LPORT_MAX); 
     for (pport=0; pport <= BCM5354X_PORT_MAX; pport++) { 
          if (SOC_PORT_P2L_MAPPING(pport) < 0) { continue; };
          bcm5354x_pmq_lport_to_blockid[SOC_PORT_P2L_MAPPING(pport)] = bcm5354x_pmq_pport_to_blockid[pport];
          bcm5354x_pmq_lport_to_index_in_block[SOC_PORT_P2L_MAPPING(pport)] = bcm5354x_pmq_pport_to_index_in_block[pport];
          bcm5354x_gport_lport_to_blockid[SOC_PORT_P2L_MAPPING(pport)] = bcm5354x_gport_pport_to_blockid[pport];
          bcm5354x_gport_lport_to_index_in_block[SOC_PORT_P2L_MAPPING(pport)] = bcm5354x_gport_pport_to_index_in_block[pport];
          bcm5354x_pgw_ge_lport_to_blockid[SOC_PORT_P2L_MAPPING(pport)] = bcm5354x_pgw_ge_pport_to_blockid[pport];
          bcm5354x_pgw_ge_lport_to_index_in_block[SOC_PORT_P2L_MAPPING(pport)] = bcm5354x_pgw_ge_pport_to_index_in_block[pport];
     };
};
