/*
 * $Id: tdm_ver.c,v 1.1 Broadcom SDK $
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenUM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2021 Broadcom Inc. All rights reserved.
 * $All Rights Reserved.$
 *
 * TDM autogenerated version
 */
#include "tdm_top.h"

void _soc_tdm_ver(int ver[8]) {
ver[0]=0;
ver[1]=5;
ver[2]=1;
ver[3]=4;
ver[4]=1;
ver[5]=1;
ver[6]=1;
ver[7]=3;
}
