# 
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenUM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.

ifeq ($(strip ${CFG_GNU_TOOLCHAIN}),1)
include ${BSP_SRC}/Makefile.gnu
else
include ${BSP_SRC}/Makefile.arm
endif


