/*
 * $Id: chipman.pm,v 1.5 Broadcom SDK n *
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenUM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2021 Broadcom Inc. All rights reserved.
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 */
#include <system.h>
const char bcm5607x_xlport_pport_to_blockid[] = 
{ 
                              -1,                               -1,                               -1,                               -1, /* Physical port 0 ~ 3 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 4 ~ 7 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 8 ~ 11 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 12 ~ 15 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 16 ~ 19 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 20 ~ 23 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 24 ~ 27 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 28 ~ 31 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 32 ~ 35 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 36 ~ 39 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 40 ~ 43 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 44 ~ 47 */
                              -1,                               -1,                 XLPORT0_BLOCK_ID,                 XLPORT0_BLOCK_ID, /* Physical port 48 ~ 51 */
                XLPORT0_BLOCK_ID,                 XLPORT0_BLOCK_ID,                 XLPORT1_BLOCK_ID,                 XLPORT1_BLOCK_ID, /* Physical port 52 ~ 55 */
                XLPORT1_BLOCK_ID,                 XLPORT1_BLOCK_ID,                 XLPORT2_BLOCK_ID,                 XLPORT2_BLOCK_ID, /* Physical port 56 ~ 59 */
                XLPORT2_BLOCK_ID,                 XLPORT2_BLOCK_ID,                               -1,                               -1, /* Physical port 60 ~ 63 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 64 ~ 67 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 68 ~ 71 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 72 ~ 75 */
                              -1,                               -1,                                                                      /* Physical port 76 ~ 78 */
};
const char bcm5607x_xlport_pport_to_index_in_block[] = 
{ 
   0,    0,    0,    0, /* Physical port 0 ~ 3 */
   0,    0,    0,    0, /* Physical port 4 ~ 7 */
   0,    0,    0,    0, /* Physical port 8 ~ 11 */
   0,    0,    0,    0, /* Physical port 12 ~ 15 */
   0,    0,    0,    0, /* Physical port 16 ~ 19 */
   0,    0,    0,    0, /* Physical port 20 ~ 23 */
   0,    0,    0,    0, /* Physical port 24 ~ 27 */
   0,    0,    0,    0, /* Physical port 28 ~ 31 */
   0,    0,    0,    0, /* Physical port 32 ~ 35 */
   0,    0,    0,    0, /* Physical port 36 ~ 39 */
   0,    0,    0,    0, /* Physical port 40 ~ 43 */
   0,    0,    0,    0, /* Physical port 44 ~ 47 */
   0,    0,    0,    1, /* Physical port 48 ~ 51 */
   2,    3,    0,    1, /* Physical port 52 ~ 55 */
   2,    3,    0,    1, /* Physical port 56 ~ 59 */
   2,    3,    0,    0, /* Physical port 60 ~ 63 */
   0,    0,    0,    0, /* Physical port 64 ~ 67 */
   0,    0,    0,    0, /* Physical port 68 ~ 71 */
   0,    0,    0,    0, /* Physical port 72 ~ 75 */
   0,    0, };
char bcm5607x_xlport_lport_to_blockid[BCM5607X_LPORT_MAX + 1] = { -1 }; 
char bcm5607x_xlport_lport_to_index_in_block[BCM5607X_LPORT_MAX + 1] = { -1 }; 
const char bcm5607x_pgw_ge_pport_to_blockid[] = 
{ 
                              -1,                               -1,                 PGW_GE0_BLOCK_ID,                 PGW_GE0_BLOCK_ID, /* Physical port 0 ~ 3 */
                PGW_GE0_BLOCK_ID,                 PGW_GE0_BLOCK_ID,                 PGW_GE0_BLOCK_ID,                 PGW_GE0_BLOCK_ID, /* Physical port 4 ~ 7 */
                PGW_GE0_BLOCK_ID,                 PGW_GE0_BLOCK_ID,                 PGW_GE0_BLOCK_ID,                 PGW_GE0_BLOCK_ID, /* Physical port 8 ~ 11 */
                PGW_GE0_BLOCK_ID,                 PGW_GE0_BLOCK_ID,                 PGW_GE0_BLOCK_ID,                 PGW_GE0_BLOCK_ID, /* Physical port 12 ~ 15 */
                PGW_GE0_BLOCK_ID,                 PGW_GE0_BLOCK_ID,                 PGW_GE1_BLOCK_ID,                 PGW_GE1_BLOCK_ID, /* Physical port 16 ~ 19 */
                PGW_GE1_BLOCK_ID,                 PGW_GE1_BLOCK_ID,                 PGW_GE1_BLOCK_ID,                 PGW_GE1_BLOCK_ID, /* Physical port 20 ~ 23 */
                PGW_GE1_BLOCK_ID,                 PGW_GE1_BLOCK_ID,                 PGW_GE1_BLOCK_ID,                 PGW_GE1_BLOCK_ID, /* Physical port 24 ~ 27 */
                PGW_GE1_BLOCK_ID,                 PGW_GE1_BLOCK_ID,                 PGW_GE1_BLOCK_ID,                 PGW_GE1_BLOCK_ID, /* Physical port 28 ~ 31 */
                PGW_GE1_BLOCK_ID,                 PGW_GE1_BLOCK_ID,                 PGW_GE2_BLOCK_ID,                 PGW_GE2_BLOCK_ID, /* Physical port 32 ~ 35 */
                PGW_GE2_BLOCK_ID,                 PGW_GE2_BLOCK_ID,                 PGW_GE2_BLOCK_ID,                 PGW_GE2_BLOCK_ID, /* Physical port 36 ~ 39 */
                PGW_GE2_BLOCK_ID,                 PGW_GE2_BLOCK_ID,                 PGW_GE2_BLOCK_ID,                 PGW_GE2_BLOCK_ID, /* Physical port 40 ~ 43 */
                PGW_GE2_BLOCK_ID,                 PGW_GE2_BLOCK_ID,                 PGW_GE2_BLOCK_ID,                 PGW_GE2_BLOCK_ID, /* Physical port 44 ~ 47 */
                PGW_GE2_BLOCK_ID,                 PGW_GE2_BLOCK_ID,                               -1,                               -1, /* Physical port 48 ~ 51 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 52 ~ 55 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 56 ~ 59 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 60 ~ 63 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 64 ~ 67 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 68 ~ 71 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 72 ~ 75 */
                              -1,                               -1,                                                                      /* Physical port 76 ~ 78 */
};
const char bcm5607x_pgw_ge_pport_to_index_in_block[] = 
{ 
   0,    0,    0,    1, /* Physical port 0 ~ 3 */
   2,    3,    4,    5, /* Physical port 4 ~ 7 */
   6,    7,    8,    9, /* Physical port 8 ~ 11 */
  10,   11,   12,   13, /* Physical port 12 ~ 15 */
  14,   15,    0,    1, /* Physical port 16 ~ 19 */
   2,    3,    4,    5, /* Physical port 20 ~ 23 */
   6,    7,    8,    9, /* Physical port 24 ~ 27 */
  10,   11,   12,   13, /* Physical port 28 ~ 31 */
  14,   15,    0,    1, /* Physical port 32 ~ 35 */
   2,    3,    4,    5, /* Physical port 36 ~ 39 */
   6,    7,    8,    9, /* Physical port 40 ~ 43 */
  10,   11,   12,   13, /* Physical port 44 ~ 47 */
  14,   15,    0,    0, /* Physical port 48 ~ 51 */
   0,    0,    0,    0, /* Physical port 52 ~ 55 */
   0,    0,    0,    0, /* Physical port 56 ~ 59 */
   0,    0,    0,    0, /* Physical port 60 ~ 63 */
   0,    0,    0,    0, /* Physical port 64 ~ 67 */
   0,    0,    0,    0, /* Physical port 68 ~ 71 */
   0,    0,    0,    0, /* Physical port 72 ~ 75 */
   0,    0, };
char bcm5607x_pgw_ge_lport_to_blockid[BCM5607X_LPORT_MAX + 1] = { -1 }; 
char bcm5607x_pgw_ge_lport_to_index_in_block[BCM5607X_LPORT_MAX + 1] = { -1 }; 
const char bcm5607x_clport_pport_to_blockid[] = 
{ 
                              -1,                               -1,                               -1,                               -1, /* Physical port 0 ~ 3 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 4 ~ 7 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 8 ~ 11 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 12 ~ 15 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 16 ~ 19 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 20 ~ 23 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 24 ~ 27 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 28 ~ 31 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 32 ~ 35 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 36 ~ 39 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 40 ~ 43 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 44 ~ 47 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 48 ~ 51 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 52 ~ 55 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 56 ~ 59 */
                              -1,                               -1,                 CLPORT0_BLOCK_ID,                 CLPORT0_BLOCK_ID, /* Physical port 60 ~ 63 */
                CLPORT0_BLOCK_ID,                 CLPORT0_BLOCK_ID,                 CLPORT1_BLOCK_ID,                 CLPORT1_BLOCK_ID, /* Physical port 64 ~ 67 */
                CLPORT1_BLOCK_ID,                 CLPORT1_BLOCK_ID,                 CLPORT2_BLOCK_ID,                 CLPORT2_BLOCK_ID, /* Physical port 68 ~ 71 */
                CLPORT2_BLOCK_ID,                 CLPORT2_BLOCK_ID,                 CLPORT3_BLOCK_ID,                 CLPORT3_BLOCK_ID, /* Physical port 72 ~ 75 */
                CLPORT3_BLOCK_ID,                 CLPORT3_BLOCK_ID,                                                                      /* Physical port 76 ~ 78 */
};
const char bcm5607x_clport_pport_to_index_in_block[] = 
{ 
   0,    0,    0,    0, /* Physical port 0 ~ 3 */
   0,    0,    0,    0, /* Physical port 4 ~ 7 */
   0,    0,    0,    0, /* Physical port 8 ~ 11 */
   0,    0,    0,    0, /* Physical port 12 ~ 15 */
   0,    0,    0,    0, /* Physical port 16 ~ 19 */
   0,    0,    0,    0, /* Physical port 20 ~ 23 */
   0,    0,    0,    0, /* Physical port 24 ~ 27 */
   0,    0,    0,    0, /* Physical port 28 ~ 31 */
   0,    0,    0,    0, /* Physical port 32 ~ 35 */
   0,    0,    0,    0, /* Physical port 36 ~ 39 */
   0,    0,    0,    0, /* Physical port 40 ~ 43 */
   0,    0,    0,    0, /* Physical port 44 ~ 47 */
   0,    0,    0,    0, /* Physical port 48 ~ 51 */
   0,    0,    0,    0, /* Physical port 52 ~ 55 */
   0,    0,    0,    0, /* Physical port 56 ~ 59 */
   0,    0,    0,    1, /* Physical port 60 ~ 63 */
   2,    3,    0,    1, /* Physical port 64 ~ 67 */
   2,    3,    0,    1, /* Physical port 68 ~ 71 */
   2,    3,    0,    1, /* Physical port 72 ~ 75 */
   2,    3, };
char bcm5607x_clport_lport_to_blockid[BCM5607X_LPORT_MAX + 1] = { -1 }; 
char bcm5607x_clport_lport_to_index_in_block[BCM5607X_LPORT_MAX + 1] = { -1 }; 
const char bcm5607x_pmqport_pport_to_blockid[] = 
{ 
                              -1,                               -1,                PMQPORT0_BLOCK_ID,                PMQPORT0_BLOCK_ID, /* Physical port 0 ~ 3 */
               PMQPORT0_BLOCK_ID,                PMQPORT0_BLOCK_ID,                PMQPORT0_BLOCK_ID,                PMQPORT0_BLOCK_ID, /* Physical port 4 ~ 7 */
               PMQPORT0_BLOCK_ID,                PMQPORT0_BLOCK_ID,                PMQPORT0_BLOCK_ID,                PMQPORT0_BLOCK_ID, /* Physical port 8 ~ 11 */
               PMQPORT0_BLOCK_ID,                PMQPORT0_BLOCK_ID,                PMQPORT0_BLOCK_ID,                PMQPORT0_BLOCK_ID, /* Physical port 12 ~ 15 */
               PMQPORT0_BLOCK_ID,                PMQPORT0_BLOCK_ID,                PMQPORT1_BLOCK_ID,                PMQPORT1_BLOCK_ID, /* Physical port 16 ~ 19 */
               PMQPORT1_BLOCK_ID,                PMQPORT1_BLOCK_ID,                PMQPORT1_BLOCK_ID,                PMQPORT1_BLOCK_ID, /* Physical port 20 ~ 23 */
               PMQPORT1_BLOCK_ID,                PMQPORT1_BLOCK_ID,                PMQPORT1_BLOCK_ID,                PMQPORT1_BLOCK_ID, /* Physical port 24 ~ 27 */
               PMQPORT1_BLOCK_ID,                PMQPORT1_BLOCK_ID,                PMQPORT1_BLOCK_ID,                PMQPORT1_BLOCK_ID, /* Physical port 28 ~ 31 */
               PMQPORT1_BLOCK_ID,                PMQPORT1_BLOCK_ID,                PMQPORT2_BLOCK_ID,                PMQPORT2_BLOCK_ID, /* Physical port 32 ~ 35 */
               PMQPORT2_BLOCK_ID,                PMQPORT2_BLOCK_ID,                PMQPORT2_BLOCK_ID,                PMQPORT2_BLOCK_ID, /* Physical port 36 ~ 39 */
               PMQPORT2_BLOCK_ID,                PMQPORT2_BLOCK_ID,                PMQPORT2_BLOCK_ID,                PMQPORT2_BLOCK_ID, /* Physical port 40 ~ 43 */
               PMQPORT2_BLOCK_ID,                PMQPORT2_BLOCK_ID,                PMQPORT2_BLOCK_ID,                PMQPORT2_BLOCK_ID, /* Physical port 44 ~ 47 */
               PMQPORT2_BLOCK_ID,                PMQPORT2_BLOCK_ID,                               -1,                               -1, /* Physical port 48 ~ 51 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 52 ~ 55 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 56 ~ 59 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 60 ~ 63 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 64 ~ 67 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 68 ~ 71 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 72 ~ 75 */
                              -1,                               -1,                                                                      /* Physical port 76 ~ 78 */
};
const char bcm5607x_pmqport_pport_to_index_in_block[] = 
{ 
   0,    0,    0,    1, /* Physical port 0 ~ 3 */
   2,    3,    4,    5, /* Physical port 4 ~ 7 */
   6,    7,    8,    9, /* Physical port 8 ~ 11 */
  10,   11,   12,   13, /* Physical port 12 ~ 15 */
  14,   15,    0,    1, /* Physical port 16 ~ 19 */
   2,    3,    4,    5, /* Physical port 20 ~ 23 */
   6,    7,    8,    9, /* Physical port 24 ~ 27 */
  10,   11,   12,   13, /* Physical port 28 ~ 31 */
  14,   15,    0,    1, /* Physical port 32 ~ 35 */
   2,    3,    4,    5, /* Physical port 36 ~ 39 */
   6,    7,    8,    9, /* Physical port 40 ~ 43 */
  10,   11,   12,   13, /* Physical port 44 ~ 47 */
  14,   15,    0,    0, /* Physical port 48 ~ 51 */
   0,    0,    0,    0, /* Physical port 52 ~ 55 */
   0,    0,    0,    0, /* Physical port 56 ~ 59 */
   0,    0,    0,    0, /* Physical port 60 ~ 63 */
   0,    0,    0,    0, /* Physical port 64 ~ 67 */
   0,    0,    0,    0, /* Physical port 68 ~ 71 */
   0,    0,    0,    0, /* Physical port 72 ~ 75 */
   0,    0, };
char bcm5607x_pmqport_lport_to_blockid[BCM5607X_LPORT_MAX + 1] = { -1 }; 
char bcm5607x_pmqport_lport_to_index_in_block[BCM5607X_LPORT_MAX + 1] = { -1 }; 
const char bcm5607x_gport_pport_to_blockid[] = 
{ 
                              -1,                               -1,                  GPORT0_BLOCK_ID,                  GPORT0_BLOCK_ID, /* Physical port 0 ~ 3 */
                 GPORT0_BLOCK_ID,                  GPORT0_BLOCK_ID,                  GPORT0_BLOCK_ID,                  GPORT0_BLOCK_ID, /* Physical port 4 ~ 7 */
                 GPORT0_BLOCK_ID,                  GPORT0_BLOCK_ID,                  GPORT1_BLOCK_ID,                  GPORT1_BLOCK_ID, /* Physical port 8 ~ 11 */
                 GPORT1_BLOCK_ID,                  GPORT1_BLOCK_ID,                  GPORT1_BLOCK_ID,                  GPORT1_BLOCK_ID, /* Physical port 12 ~ 15 */
                 GPORT1_BLOCK_ID,                  GPORT1_BLOCK_ID,                  GPORT2_BLOCK_ID,                  GPORT2_BLOCK_ID, /* Physical port 16 ~ 19 */
                 GPORT2_BLOCK_ID,                  GPORT2_BLOCK_ID,                  GPORT2_BLOCK_ID,                  GPORT2_BLOCK_ID, /* Physical port 20 ~ 23 */
                 GPORT2_BLOCK_ID,                  GPORT2_BLOCK_ID,                  GPORT3_BLOCK_ID,                  GPORT3_BLOCK_ID, /* Physical port 24 ~ 27 */
                 GPORT3_BLOCK_ID,                  GPORT3_BLOCK_ID,                  GPORT3_BLOCK_ID,                  GPORT3_BLOCK_ID, /* Physical port 28 ~ 31 */
                 GPORT3_BLOCK_ID,                  GPORT3_BLOCK_ID,                  GPORT4_BLOCK_ID,                  GPORT4_BLOCK_ID, /* Physical port 32 ~ 35 */
                 GPORT4_BLOCK_ID,                  GPORT4_BLOCK_ID,                  GPORT4_BLOCK_ID,                  GPORT4_BLOCK_ID, /* Physical port 36 ~ 39 */
                 GPORT4_BLOCK_ID,                  GPORT4_BLOCK_ID,                  GPORT5_BLOCK_ID,                  GPORT5_BLOCK_ID, /* Physical port 40 ~ 43 */
                 GPORT5_BLOCK_ID,                  GPORT5_BLOCK_ID,                  GPORT5_BLOCK_ID,                  GPORT5_BLOCK_ID, /* Physical port 44 ~ 47 */
                 GPORT5_BLOCK_ID,                  GPORT5_BLOCK_ID,                               -1,                               -1, /* Physical port 48 ~ 51 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 52 ~ 55 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 56 ~ 59 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 60 ~ 63 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 64 ~ 67 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 68 ~ 71 */
                              -1,                               -1,                               -1,                               -1, /* Physical port 72 ~ 75 */
                              -1,                               -1,                                                                      /* Physical port 76 ~ 78 */
};
const char bcm5607x_gport_pport_to_index_in_block[] = 
{ 
   0,    0,    0,    1, /* Physical port 0 ~ 3 */
   2,    3,    4,    5, /* Physical port 4 ~ 7 */
   6,    7,    0,    1, /* Physical port 8 ~ 11 */
   2,    3,    4,    5, /* Physical port 12 ~ 15 */
   6,    7,    0,    1, /* Physical port 16 ~ 19 */
   2,    3,    4,    5, /* Physical port 20 ~ 23 */
   6,    7,    0,    1, /* Physical port 24 ~ 27 */
   2,    3,    4,    5, /* Physical port 28 ~ 31 */
   6,    7,    0,    1, /* Physical port 32 ~ 35 */
   2,    3,    4,    5, /* Physical port 36 ~ 39 */
   6,    7,    0,    1, /* Physical port 40 ~ 43 */
   2,    3,    4,    5, /* Physical port 44 ~ 47 */
   6,    7,    0,    0, /* Physical port 48 ~ 51 */
   0,    0,    0,    0, /* Physical port 52 ~ 55 */
   0,    0,    0,    0, /* Physical port 56 ~ 59 */
   0,    0,    0,    0, /* Physical port 60 ~ 63 */
   0,    0,    0,    0, /* Physical port 64 ~ 67 */
   0,    0,    0,    0, /* Physical port 68 ~ 71 */
   0,    0,    0,    0, /* Physical port 72 ~ 75 */
   0,    0, };
char bcm5607x_gport_lport_to_blockid[BCM5607X_LPORT_MAX + 1] = { -1 }; 
char bcm5607x_gport_lport_to_index_in_block[BCM5607X_LPORT_MAX + 1] = { -1 }; 



void bcm5607x_init_port_block_map(uint16 devid, uint16 revid) { 
     int pport;
     sal_memset(bcm5607x_xlport_lport_to_blockid, -1, BCM5607X_LPORT_MAX);
     sal_memset(bcm5607x_xlport_lport_to_index_in_block, 0, BCM5607X_LPORT_MAX); 
     sal_memset(bcm5607x_pgw_ge_lport_to_blockid, -1, BCM5607X_LPORT_MAX);
     sal_memset(bcm5607x_pgw_ge_lport_to_index_in_block, 0, BCM5607X_LPORT_MAX); 
     sal_memset(bcm5607x_clport_lport_to_blockid, -1, BCM5607X_LPORT_MAX);
     sal_memset(bcm5607x_clport_lport_to_index_in_block, 0, BCM5607X_LPORT_MAX); 
     sal_memset(bcm5607x_pmqport_lport_to_blockid, -1, BCM5607X_LPORT_MAX);
     sal_memset(bcm5607x_pmqport_lport_to_index_in_block, 0, BCM5607X_LPORT_MAX); 
     sal_memset(bcm5607x_gport_lport_to_blockid, -1, BCM5607X_LPORT_MAX);
     sal_memset(bcm5607x_gport_lport_to_index_in_block, 0, BCM5607X_LPORT_MAX); 
     for (pport=0; pport <= BCM5607X_PORT_MAX; pport++) { 
          if (SOC_PORT_P2L_MAPPING(pport) < 0) { continue; };
          bcm5607x_xlport_lport_to_blockid[SOC_PORT_P2L_MAPPING(pport)] = bcm5607x_xlport_pport_to_blockid[pport];
          bcm5607x_xlport_lport_to_index_in_block[SOC_PORT_P2L_MAPPING(pport)] = bcm5607x_xlport_pport_to_index_in_block[pport];
          bcm5607x_pgw_ge_lport_to_blockid[SOC_PORT_P2L_MAPPING(pport)] = bcm5607x_pgw_ge_pport_to_blockid[pport];
          bcm5607x_pgw_ge_lport_to_index_in_block[SOC_PORT_P2L_MAPPING(pport)] = bcm5607x_pgw_ge_pport_to_index_in_block[pport];
          bcm5607x_clport_lport_to_blockid[SOC_PORT_P2L_MAPPING(pport)] = bcm5607x_clport_pport_to_blockid[pport];
          bcm5607x_clport_lport_to_index_in_block[SOC_PORT_P2L_MAPPING(pport)] = bcm5607x_clport_pport_to_index_in_block[pport];
          bcm5607x_pmqport_lport_to_blockid[SOC_PORT_P2L_MAPPING(pport)] = bcm5607x_pmqport_pport_to_blockid[pport];
          bcm5607x_pmqport_lport_to_index_in_block[SOC_PORT_P2L_MAPPING(pport)] = bcm5607x_pmqport_pport_to_index_in_block[pport];
          bcm5607x_gport_lport_to_blockid[SOC_PORT_P2L_MAPPING(pport)] = bcm5607x_gport_pport_to_blockid[pport];
          bcm5607x_gport_lport_to_index_in_block[SOC_PORT_P2L_MAPPING(pport)] = bcm5607x_gport_pport_to_index_in_block[pport];
     };
};
