/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 *
 * $Id: $
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenUM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2021 Broadcom Inc. All rights reserved.
 */

#include "system.h"

#ifdef CFG_CHIP_SYMBOLS_INCLUDED
/* Block types */
const char *bcm5607x_blktype_names[] = {
    "avs",
    "clport",
    "cmic",
    "epipe",
    "gport",
    "ipipe",
    "iproc",
    "macsec",
    "mmu",
    "pgw_ge",
    "pmqport",
    "ser",
    "taf",
    "top",
    "xlport"
};

/* Block structures */
static chip_block_t bcm5607x_blocks[] =
{
    { BCM5607X_BLKTYPE_CLPORT,          20,   CHIP_PBMP_3(0x00000000, 0xc0000000, 0x00000003) },
    { BCM5607X_BLKTYPE_CLPORT,          21,   CHIP_PBMP_3(0x00000000, 0x00000000, 0x0000003c) },
    { BCM5607X_BLKTYPE_CLPORT,          22,   CHIP_PBMP_3(0x00000000, 0x00000000, 0x000003c0) },
    { BCM5607X_BLKTYPE_CLPORT,          23,   CHIP_PBMP_3(0x00000000, 0x00000000, 0x00003c00) },
    { BCM5607X_BLKTYPE_GPORT,           33,   CHIP_PBMP_1(0x000003fc) },
    { BCM5607X_BLKTYPE_GPORT,           34,   CHIP_PBMP_1(0x0003fc00) },
    { BCM5607X_BLKTYPE_GPORT,           37,   CHIP_PBMP_1(0x03fc0000) },
    { BCM5607X_BLKTYPE_GPORT,           38,   CHIP_PBMP_2(0xfc000000, 0x00000003) },
    { BCM5607X_BLKTYPE_GPORT,           41,   CHIP_PBMP_2(0x00000000, 0x000003fc) },
    { BCM5607X_BLKTYPE_GPORT,           42,   CHIP_PBMP_2(0x00000000, 0x0003fc00) },
    { BCM5607X_BLKTYPE_PMQPORT,         35,   CHIP_PBMP_1(0x00000000) },
    { BCM5607X_BLKTYPE_PMQPORT,         39,   CHIP_PBMP_1(0x00000000) },
    { BCM5607X_BLKTYPE_PMQPORT,         43,   CHIP_PBMP_1(0x00000000) },
    { BCM5607X_BLKTYPE_XLPORT,          32,   CHIP_PBMP_2(0x00000000, 0x003c0000) },
    { BCM5607X_BLKTYPE_XLPORT,          36,   CHIP_PBMP_2(0x00000000, 0x03c00000) },
    { BCM5607X_BLKTYPE_XLPORT,          40,   CHIP_PBMP_2(0x00000000, 0x3c000000) },
    { BCM5607X_BLKTYPE_PGW_GE,           4,   CHIP_PBMP_1(0x0003fffc) },
    { BCM5607X_BLKTYPE_PGW_GE,           5,   CHIP_PBMP_2(0xfffc0000, 0x00000003) },
    { BCM5607X_BLKTYPE_PGW_GE,           6,   CHIP_PBMP_2(0x00000000, 0x0003fffc) },
    { BCM5607X_BLKTYPE_IPIPE,           10,   CHIP_PBMP_3(0xffffffff, 0xffffffff, 0x00000003) },
    { BCM5607X_BLKTYPE_EPIPE,           11,   CHIP_PBMP_3(0xffffffff, 0xffffffff, 0x00000003) },
    { BCM5607X_BLKTYPE_MMU,             12,   CHIP_PBMP_3(0xffffffff, 0xffffffff, 0x00000003) },
    { BCM5607X_BLKTYPE_IPROC,           15,   CHIP_PBMP_1(0x00000001) },
    { BCM5607X_BLKTYPE_TOP,             16,   CHIP_PBMP_3(0xfffffffd, 0xffffffff, 0x00003fff) },
    { BCM5607X_BLKTYPE_SER,             17,   CHIP_PBMP_3(0xfffffffd, 0xffffffff, 0x00003fff) },
    { BCM5607X_BLKTYPE_AVS,             18,   CHIP_PBMP_3(0xfffffffd, 0xffffffff, 0x00003fff) },
    { BCM5607X_BLKTYPE_MACSEC,          19,   CHIP_PBMP_2(0xffffffff, 0x0000ffff) }
};

/* Symbol table */
extern symbols_t bcm5607x_symbols;

static uint32
bcm5607x_blockport_addr(int block, int lane, uint32 offset, uint32 idx)
{
    uint32_t addr;

    if (lane < 0) {
        /* Default block/port calculation for memories */
        addr = offset;
        addr += idx;
    } else {
        /* Default block/port calculation for registers */
        addr = (offset | lane);

        /* MMU */
        if (block == 12) {
            addr += (idx << 8);
        }
    }
    return addr;
}

/* Chip information structure */
chip_info_t bcm5607x_chip_info = {
    /* block types */
    15,
    bcm5607x_blktype_names,

    /* blocks */
    27,
    bcm5607x_blocks,

    /* Address calculation */
    bcm5607x_blockport_addr,

    /* Valid ports for this chip */
    CHIP_PBMP_3(0xfffffffd, 0xffffffff, 0x00003fff),

    /* Use the static per-chip symbol tables */
    &bcm5607x_symbols,
};

#endif /* CFG_CHIP_SYMBOLS_INCLUDED */
