#! /usr/bin/env python
###############################################################################
#
# This script is used to convert files under $UM/systems/bcmxxx/binfs
# into C header files and then put C header files to $UM/bcmxxx/include/binfs
# And instance all C header files at $UM/bcmxxx/src/binfsi_file_list.c.
#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenUM/master/Legal/LICENSE file.
# 
# Copyright 2007-2021 Broadcom Inc. All rights reserved.
#
###############################################################################

import os.path
import re
import struct
import sys
from datetime import date

header = """/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 * Tool: tools/genbinfs.py
 * Date: {date}
 *
 * $Copyright: (c) 2021 Broadcom Corp.
 * All Rights Reserved. $
 */

#include <system.h>
#include <binfs.h>
"""

def binfs_node_name_get(filename) :
    #print filename
    return "binfs_file_" + re.sub(r"\W", "_", filename)

def binfs_node_data_name_get(filename) :
    return "binfs_file_data_" + re.sub(r"\W", "_", filename)

def genbin2h(filename, rootdir, outdir):

    incstart = """
#ifndef {file}
#define {file}
"""
    incend = """
#endif /* {file} */
"""

    arraydef = """
/*! {description} {length} bytes. */
static const {dtype} {array}[] = {{{content}}};
"""

    binfsdef = """
/*! {description} */
const {dtype} {name} = {{
    "{filename}",
    {data},
    sizeof({data})
}};
"""

    basename = os.path.basename(filename)
    basename = re.sub(rootdir + "/*", "", filename)
    outputfile = os.path.join(outdir, basename) + ".h"
    dirname = os.path.dirname(outputfile)
    reltive_input = re.sub(topdir + "/*", "", filename)
#    reltive_output = re.sub(topdir + "/*", "", outputfile)
    reltive_output = outputfile;
    arrayname = binfs_node_data_name_get(basename)
    array = ""
    length = 0

    print("Convert {0}".format(reltive_input))
    if not os.path.isdir(dirname):
        os.makedirs(dirname)
    outfd = open(outputfile, "wt")
    fd = open(filename, "rb")

    outfd.write(header)
    s = re.sub(r"\W", "_", os.path.basename(reltive_input))

    outfd.write(incstart.format(file=s.upper()))

    while True:
        block = fd.read(16)

        if len(block):
            # Indent 4 space.
            array += "\n    "

        i = 0
        for b in block:
            # Python 2/3 compat
            if type(b) is str:
                b = ord(b)
            array += "0x{:02X},".format(b)
            i = i + 1
            if i < len(block):
                array += " "

        if len(block) == 0:
           break

        length += len(block)

    if len(array):
        array += "\n"

    fd.close()
    outfd.write(arraydef.format(dtype="uint8", \
                                length=length, \
                                array=binfs_node_data_name_get(basename), \
                content=array, \
                description="File data of " + reltive_input))
    outfd.write(binfsdef.format(dtype="binfs_file_t", \
                                description="File structure of " + reltive_input, \
                                name=binfs_node_name_get(basename), \
                                filename= basename, \
                                data = binfs_node_data_name_get(basename)))

    outfd.write(incend.format(file=s.upper()))

    outfd.close()
    return reltive_output

def genbinfs_node_list(incdir, outfile, filelist):
    outfd = open(outfile, "w")
    extern_defs = """#include <{file}>\n"""
    binfs_node_list = "\n/* List for files in binfs. */\nconst binfs_file_t *binfs_file_list[] = {\n"
    extern = ""
    for f in filelist:
        #print f + ".\n"
        #print incdir
        s = re.sub(incdir + "/", "", f)
        extern += extern_defs.format(file=s)
        s = re.sub("\.h$","", s)
        binfs_node_name = binfs_node_name_get(s)
        binfs_node_list += ("    &" + binfs_node_name + ",\n")

    binfs_node_list += "    NULL\n};\n\n"
    outfd.write(header.format(date=date.today()))
    outfd.write(extern)
    outfd.write(binfs_node_list)
    outfd.close()
    return


def genbinfs(rootdir, outdir, incdir):
    filelist = []
    pattern = re.compile('.+\.bin$')
    for dirPath, dirNames, fileNames in os.walk(rootdir):
        for f in fileNames:
            if (pattern.match(f) == None):
                continue
            infile = os.path.join(dirPath, f)

            outfile = genbin2h(infile, rootdir, incdir)
            #outfile = os.path.join(incdir, os.path.basename(outfile))
            filelist.append(outfile)

    genbinfs_node_list(incdir, os.path.join(outdir, "binfs_file_list.c"), filelist)


def main():
    global topdir
    pwd = os.getenv('PWD')
    topdir = os.path.abspath(pwd + "../../../")
    rootdir = pwd + "/binfs"
    system_inc_dir = pwd + "/include/binfs"
    system_src_dir = pwd + "/"
    linux_build = os.path.islink("configs")

    if (linux_build):
        system_env = os.getenv('SYSTEM')
        #print "system_env " + system_env
        if (system_env == None):
            print("The system id is undefined.")
            sys_exit(1)
        rootdir = os.path.abspath(pwd + "../../") + "/" + system_env + "/binfs"
        system_inc_dir = "systems/" + system_env + "/include/binfs"
        system_src_dir = pwd + "/"

    #print rootdir + "\n"
    outdir = os.path.join(topdir, system_src_dir)
    incdir = os.path.join(topdir, system_inc_dir)
    #print outdir
    #print incdir
    genbinfs(rootdir, outdir, incdir)

if __name__ == "__main__":
    main()
